export enum HttpErrorType {
  INVALID_TOKEN = 'INVALID_TOKEN',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  PERMISSION_EXISTS = 'PERMISSION_EXISTS',
  ROLE_EXISTS = 'ROLE_EXISTS',
  USER_EXISTS = 'USER_EXISTS',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  BLOCKED_USER = 'BLOCKED_USER',
  INACTIVE_USER = 'INACTIVE_USER',
  FOREIGN_KEY_CONFLICT = 'FOREIGN_KEY_CONFLICT',
}
